server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
  port: 8080
  forward-headers-strategy: framework

spring:
  profiles:
    active: prod
  jmx:
    enabled: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 16384MB
      max-request-size: 16384MB
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
  redis:
    timeout: 30000
    connectTimeout: 60000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5
    client-type: jedis
  cache:
    type: redis
    redis:
      # 如果指定了前缀就用我们指定的前缀，如果没有就默认使用缓存的名字作为前缀
      use-key-prefix: true
      # 是否缓存空值，防止缓存穿透
      cache-null-values: true
      # 缓存的过期时间，单位是毫秒
      time-to-live: 86400000
  mvc:
    log-resolved-exception: true
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

mybatis-plus:
  type-aliases-package: top.liheji.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      table-prefix: server_
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true

logging:
  level:
    root: info
    top.liheji.server: info
  config: classpath:logback-spring.xml

permission:
  create: false
  list:
    - table: auth_group
      all: 权限分组(角色)
    - table: auth_permission
      add: 添加权限
      change: 修改权限描述
      view: 查看权限
    - table: server_account
      add: 创建用户(生成注册码)
      change: 修改所有用户信息
      delete: 逻辑删除用户
      view: 查看所有用户信息
    - table: server_upload_info
      add: 上传文件
      delete: 删除上传的文件
      view: 查看上传的文件
      download: 下载上传的文件
    - table: latex_account
      use: 使用Latex公式识别
    - table: server_websocket
      use: 使用WebSocket(不存在的表)
    - table: server_wakeup
      use: 使用WakeUp格式化(不存在的表)