server:
  servlet:
    session:
      tracking-modes: cookie
      cookie:
        http-only: true
  port: 8080
  forward-headers-strategy: framework

spring:
  jmx:
    enabled: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      enabled: true
      max-file-size: 16384MB
      max-request-size: 16384MB
  datasource: # 配置数据库连接
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/数据库名称?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: 用户名
    password: 密码
  mail:
    host: smtp.qq.com
    username: 邮箱账号
    password: 邮箱认证密码
    port: 587
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 30000
    connectTimeout: 60000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 5
  cache:
    type: redis
    redis:
      # 如果指定了前缀就用我们指定的前缀，如果没有就默认使用缓存的名字作为前缀
      use-key-prefix: true
      # 是否缓存空值，防止缓存穿透
      cache-null-values: true
      # 缓存的过期时间，单位是毫秒
      time-to-live: 86400000

ums:
  oauth:
    qq:
      client-id: KEY
      client-secret: SECRET
    github:
      client-id: KEY
      client-secret: SECRET
    gitee:
      client-id: KEY
      client-secret: SECRET
    # 登录信息
    domain: http://localhost:8000
    auth-login-url-prefix: /oauth2/authorization
    redirect-url-prefix: /oauth2/login
    # 自动注册
    auto-sign-up: false
    sign-up-url: /
    enable-user-connection-and-auth-token-table: false
    enable-auth-token-table: false


mybatis-plus:
  type-aliases-package: top.liheji.pojo
  mapper-locations: classpath:mapper/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      table-prefix: server_
  configuration:
    cache-enabled: true
    lazy-loading-enabled: true

logging:
  level:
    root: info
    top.liheji.server: info
  config: classpath:log4j2.xml

permission:
  list:
    - table: auth_group
      all: 权限分组(角色)
    - table: auth_permission
      add: 添加权限
      change: 修改权限描述
      view: 查看权限
    - table: server_account
      add: 创建用户(生成注册码)
      change: 修改所有用户信息
      delete: 逻辑删除用户
      view: 查看所有用户信息
    - table: server_uploadinfo
      add: 上传文件
      delete: 删除上传的文件
      view: 查看上传的文件
      download: 下载上传的文件
    - table: latex_account
      use: 使用Latex公式识别
    - table: server_websocket
      use: 使用WebSocket(不存在的表)
    - table: server_wakeup
      use: 使用WakeUp格式化(不存在的表)
  create: false